version: '3'
volumes:
  dummy: 
services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.41.1-jammy
    volumes:
      - ./:/app/
      - dummy:/app/node_modules
    environment:
      -  DISPLAY=host.docker.internal:0.0
    working_dir: /app
    command: bash -c "
        corepack enable pnpm &&
        pnpm install &&
        pnpm e2e
      "
